name: Build and push to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
      

    - name: Installing my packages
      run: yarn install --frozen-lockfile

    - name: Build my App  
      run: yarn build
      env:
        NEXT_PUBLIC_BASE_PATH: /RWD-sem5-assignment-1
    - run: touch ./out/.nojekyll
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: out # The folder the action should deploy.
